### ISSUE TITLE
testPMTK3 failed

### ISSUE THREAD

**Issue by JKNA** [probml/pmtk3#107]
Environment: Win8.1 x64 + MATLAB R2015b
Successfully initialized PMTK3, however, failed to pass minimal test provided by testPMTK3.m. The following is the output:
```
Error using evalin
 Undefined function or variable 'nsamples'.
 Error in SetDefaultValue (line 24)
 isempty(evalin('caller', argName))
 Error in hmmSample (line 9)
 SetDefaultValue(3, 'nsamples', 1);
 Error in hmmDiscreteTest (line 26)
[observed, hidden] = hmmSample(trueModel, len);
 Error in testPmtk3 (line 68)
hmmDiscreteTest;
```

**Comment by yrazin** [comment]
Environment Win7 x64 MATLAB2015b
This can be solved by replacing l.24 in SetDefaultValue.m to evalin('caller','~exist(''nsamples'')')
