### ISSUE TITLE
Parameters are not set in condDiscreteProdCpdFit

### ISSUE THREAD

**Issue by flokadillo** [probml/pmtk3#128]
There seems to be a small error in `GraphicalModels/cpd/condDiscreteProdCpdCreate.m`. In function `condDiscreteProdCpdFit`, the variable `T` is computed but is not returned. I guess we should add a line saying `CPD.T = T;` to the end of the function.

**Comment by murphyk** [comment]
Please make a pull request with the bug fix.

**Comment by flokadillo** [comment]
closing due as the issue is quite old now
